version: '2.4'

services:
    mysql:
        image: mysql/mysql-server:5.7
        container_name: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-use-native-aio=0
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_ROOT_HOST: '%'
        ports:
        - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

    service:
        image: han.server:latest
        container_name: service
        depends_on: 
            mysql:
                condition: service_healthy
        environment:
            ASPNETCORE_URLS: http://+:8080
            DATABASE_CONNECTION_STRING: Server=mysql;Uid=root;Pwd=admin
            DATABASE_NAME: Han
        ports:
        - 8080:8080
