version: '2.4'

services:
    mysql:
        container_name: mysql
        image: mysql/mysql-server:5.7
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_ROOT_HOST: '%'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-use-native-aio=0
        ports:
        - 3306:3306